#!/bin/bash

build() {

	add_systemd_unit tutamen-ask-password.path
	add_systemd_unit tutamen-ask-password.service
	add_binary       /usr/lib/systemd/tutamen-ask-password
	add_symlink      /etc/systemd/system/default.target.wants/tutamen-ask-password.path \
		         /usr/lib/systemd/system/tutamen-ask-password.path

	add_file /etc/ssl/certs/ca-certificates.crt
	add_file /home/matt/.config/pytutamen_client/accounts/9b6f28e7-fe91-44c1-bb9f-7a400bbc2e57/clients/a2a2883b-45f4-42ef-ad5a-8e3869f8874d/key.pem         /tut.key
	add_file /home/matt/.config/pytutamen_client/accounts/9b6f28e7-fe91-44c1-bb9f-7a400bbc2e57/clients/a2a2883b-45f4-42ef-ad5a-8e3869f8874d/test_ac_crt.pem /tut.crt
}

help() {
	cat <<HELPEOF
tutamen
HELPEOF
}
