#!/bin/bash

build() {

	if [[ ! $TUTAMEN_CONFIG ]]; then
		error "TUTAMEN_CONFIG must be specified as an environmental variable"
		return 1
	elif [[ ! -d $TUTAMEN_CONFIG ]]; then
		error "TUTAMEN_CONFIG must point to a directory"
		return 1
	fi

	add_dir /root/.config
	cp -a "$TUTAMEN_CONFIG" "$BUILDROOT"/root/.config/

	add_file         /etc/ssl/certs/ca-certificates.crt

	add_systemd_unit tutamen-ask-password.path
	add_systemd_unit tutamen-ask-password.service
	add_binary       /usr/lib/systemd/tutamen-ask-password
	add_symlink      /etc/systemd/system/default.target.wants/tutamen-ask-password.path \
		         /usr/lib/systemd/system/tutamen-ask-password.path
}

help() {
	cat <<HELPEOF
sd-tutamen copies a tutamen config directory specified by \$TUTAMEN_CONFIG
to /root/.confg/ on the initramfs which can respond to systemd-cryptsetup's
ask-password request during early boot. The normal password prompt will
still be available.

The config section and [ask-password] and UUID values for 'collection' and
'secret' must be available.
HELPEOF
}
